### ISSUE TITLE
Turning on “Alfred filters results” allows for typing to filter layouts

### ISSUE THREAD

**Issue by vitorgalvao** [AdamNSmith/Alfred_X_Moom#1]
Refs [a solution given in the forum](https://www.alfredforum.com/topic/18473-moom-switch-between-custom-moom-snapshots/#comment-100537). Just by ticking the “Alfred filters results” checkbox in the Script Filter, its usability is increased.

I’d submit a PR instead of an issue, but there’s no code in the repo.

**Comment by praxder** [comment]
Fixed (and published a new release). I also committed the code so people can make PR's for future changes. Thanks for the feedback.
